---
- name: Copy index.html
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started

    # - name: Copy file with owner and permissions
    #   ansible.builtin.copy:
    #       src: /home/ubuntu/ansible/index.html
    #       dest: /var/www/html/index.html
    #       mode: '744'